run:
  skip-dirs:
    - ^tools$
    - ^examples$
    - ^bench-output$
    - ^cmd/flow-worker$
    - ^cmd/flow-assets$
    - ^examples/.*$
  timeout: 5m
  tests: true

linters:
  disable-all: false
  enable:
    - govet
    - staticcheck
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - unused
    - ineffassign
    - typecheck
    - bodyclose

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - errcheck
      # ignore errcheck findings that match these simple function names
      text: "Close"
    - linters:
        - errcheck
      text: "Write"
    - linters:
        - errcheck
      text: "Flush"
    - path: _test\.go$
      text: ""
    
linters-settings: {}

exclude:
  - _gen.go