package routegen

import (
	"fmt"
	"os"
	"path/filepath"

	yaml "gopkg.in/yaml.v3"
)

// GenerateFromFile reads a YAML manifest mapping route names to paths and
// writes a simple Go file at outPath with a map of routes. This is intentionally
// small and robust to ensure the CLI can import the package during development.
func GenerateFromFile(manifestPath, outPath string) error {
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return fmt.Errorf("read manifest: %w", err)
	}
	var m map[string]string
	if err := yaml.Unmarshal(data, &m); err != nil {
		return fmt.Errorf("parse manifest: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return fmt.Errorf("mkdir: %w", err)
	}

	f, err := os.Create(outPath)
	if err != nil {
		return fmt.Errorf("create out: %w", err)
	}
	defer f.Close()

	// write simple generated file
	fmt.Fprintln(f, "package router")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "// Code generated by flow routegen; DO NOT EDIT.")
	fmt.Fprintln(f, "")
	fmt.Fprintln(f, "var Routes = map[string]string{")
	for name, path := range m {
		fmt.Fprintf(f, "\t%q: %q,\n", name, path)
	}
	fmt.Fprintln(f, "}")

	return nil
}
