package generator

var controllerTmpl = `// Code generated by flow generate; DO NOT EDIT.
package {{.Package}}

import (
    "net/http"
    flow "github.com/dministrator/flow/pkg/flow"
)

// {{.Controller}} is a simple controller generated by Flow.
type {{.Controller}} struct{ *flow.Controller }

func New{{.Controller}}(app *flow.App) *{{.Controller}} {
    return &{{.Controller}}{Controller: flow.NewController(app)}
}

func (c *{{.Controller}}) Index(ctx *flow.Context) {
    ctx.JSON(200, map[string]string{"action": "index"})
}

func (c *{{.Controller}}) Show(ctx *flow.Context) {
    id := ctx.Param("id")
    ctx.JSON(200, map[string]string{"id": id})
}
`

// removed unused generated model template (bunModelTmpl is used instead)

// bunModelTmpl is a model template that includes bun struct tags which are
// friendly to the bun ORM adapter. Generators will use this when bun is the
// chosen adapter.
var bunModelTmpl = `// Code generated by flow generate; DO NOT EDIT.
package {{.Package}}

import (
    "context"
    "github.com/dministrator/flow/pkg/flow"
{{.ExtraImports}}
)

// {{.Model}} is a generated model using bun struct tags.
type {{.Model}} struct {
    flow.Model
{{.FieldsCode}}
}

// Save persists the model. It inserts when ID==0 or updates otherwise.
func (m *{{.Model}}) Save(ctx context.Context, app *flow.App) error {
    if m.ID == 0 {
        return flow.Insert(ctx, app, m)
    }
    return flow.Update(ctx, app, m)
}

// Delete removes the model from the database.
func (m *{{.Model}}) Delete(ctx context.Context, app *flow.App) error {
    return flow.Delete(ctx, app, m)
}
`

var migrationUpTmpl = `-- Migration: {{.Timestamp}}_create_{{.Table}}.up.sql
-- Generated by flow
CREATE TABLE IF NOT EXISTS {{.Table}} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
{{.Columns}}
);
{{.ExtrasUp}}
`

var migrationDownTmpl = `-- Migration: {{.Timestamp}}_create_{{.Table}}.down.sql
-- Generated by flow
{{.ExtrasDown}}
DROP TABLE IF EXISTS {{.Table}};
`

var viewIndexTmpl = `<h1>{{.Title}} index</h1>
<ul>
{{range .Items}}  <li>{{.}}</li>
{{end}}</ul>`

var viewShowTmpl = `<h1>{{.Title}} show</h1>
<p>ID: {{.ID}}</p>`

var viewNewTmpl = `<h1>New {{.Title}}</h1>
<form method="post" action="">
    <!-- TODO: fields -->
    <button type="submit">Create</button>
</form>`

var viewEditTmpl = `<h1>Edit {{.Title}}</h1>
<form method="post" action="">
    <!-- TODO: fields -->
    <button type="submit">Save</button>
</form>`

// Admin templates
var adminControllerTmpl = `// Code generated by flow generate admin; DO NOT EDIT.
package controllers

import (
    "github.com/dministrator/flow/pkg/flow"
)

type {{.Controller}} struct{ *flow.Controller }

func New{{.Controller}}(app *flow.App) *{{.Controller}} {
    return &{{.Controller}}{Controller: flow.NewController(app)}
}

func (c *{{.Controller}}) Index(ctx *flow.Context) {
    // TODO: replace with real list retrieval
    ctx.Render("admin/{{.Name}}/index", map[string]interface{}{"Title": "{{.Title}}"}, ctx)
}

func (c *{{.Controller}}) Show(ctx *flow.Context) {
    id := ctx.Param("id")
    ctx.Render("admin/{{.Name}}/show", map[string]interface{}{"Title": "{{.Title}}", "ID": id}, ctx)
}

func (c *{{.Controller}}) New(ctx *flow.Context) {
    ctx.Render("admin/{{.Name}}/new", map[string]interface{}{"Title": "New {{.Title}}"}, ctx)
}

func (c *{{.Controller}}) Create(ctx *flow.Context) {
    // TODO: implement creation logic (bind form, persist)
    ctx.Redirect(302, "/admin/{{.Name}}")
}

func (c *{{.Controller}}) Edit(ctx *flow.Context) {
    id := ctx.Param("id")
    ctx.Render("admin/{{.Name}}/edit", map[string]interface{}{"Title": "Edit {{.Title}}", "ID": id}, ctx)
}

func (c *{{.Controller}}) Update(ctx *flow.Context) {
    // TODO: implement update logic
    ctx.Redirect(302, "/admin/{{.Name}}")
}

func (c *{{.Controller}}) Delete(ctx *flow.Context) {
    // TODO: implement delete logic
    ctx.Redirect(302, "/admin/{{.Name}}")
}

// MountAdminRoutes registers admin routes for this resource.
func MountAdmin{{.Controller}}Routes(app *flow.App) {
    r := flow.NewRouter(app)
    ctrl := New{{.Controller}}(app)
    base := "/admin/{{.Name}}"
    r.Get(base, ctrl.Index)
    r.Get(base+"/new", ctrl.New)
    r.Post(base, ctrl.Create)
    r.Get(base+"/:id", ctrl.Show)
    r.Get(base+"/:id/edit", ctrl.Edit)
    r.Post(base+"/:id", ctrl.Update)
    r.Post(base+"/:id/delete", ctrl.Delete)
    app.Mount(r)
}
`

var viewAdminIndexTmpl = `<h1>{{.Title}} - index</h1>
<p><a href="/admin/{{.Name}}/new">New</a></p>
<ul>
  <!-- TODO: render items -->
  <li>Example item</li>
</ul>`

var viewAdminShowTmpl = `<h1>{{.Title}} - show</h1>
<p>ID: {{.ID}}</p>
<p><a href="/admin/{{.Name}}">Back</a></p>`

var viewAdminNewTmpl = `<h1>New {{.Title}}</h1>
<form method="post" action="/admin/{{.Name}}">
    <!-- TODO: form fields -->
    <button type="submit">Create</button>
</form>`

var viewAdminEditTmpl = `<h1>Edit {{.Title}}</h1>
<form method="post" action="/admin/{{.Name}}/{{.ID}}">
    <!-- TODO: form fields -->
    <button type="submit">Save</button>
</form>`

var adminLayoutTmpl = `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Admin - {{.Title}}</title>
  <link rel="stylesheet" href="/assets/admin/admin.css">
  <style>body{font-family:Arial,Helvetica,sans-serif;padding:20px}</style>
</head>
<body>
  <nav><a href="/admin">Admin</a> | <a href="/">Home</a></nav>
  <div id="flash">{{/* TODO: flash messages */}}</div>
  <main>{{ template "content" . }}</main>
</body>
</html>`

var adminCSSTmpl = `/* Minimal admin CSS */
body { background:#f7f7f7; color:#111 }
nav { margin-bottom: 1em }
main { background:#fff; padding:1em; border-radius:6px }
`

var adminReadmeTmpl = `# Admin scaffold

This folder contains generated admin UI scaffolding (controllers, views, routes).

To mount the admin routes in your application main, call the generated mount function in your main.go. For example:

    // inside main
    MountAdminPostsRoutes(app)

Replace or implement TODOs in the generated controller actions to add persistence and validation.
`

// Auth templates
var authControllerTmpl = `// Code generated by flow generate auth; DO NOT EDIT.
package controllers

import (
    "net/http"
    "github.com/dministrator/flow/pkg/flow"
    "golang.org/x/crypto/bcrypt"
    "context"
)

// AuthController provides simple login/logout handlers backed by sessions.
type AuthController struct{ *flow.Controller }

func NewAuthController(app *flow.App) *AuthController {
    return &AuthController{Controller: flow.NewController(app)}
}

// Login renders the login page (GET) and handles authentication (POST).
func (c *AuthController) Login(ctx *flow.Context) {
    if ctx.R.Method == http.MethodGet {
        _ = ctx.Render("auth/login", map[string]interface{}{"Title": "Login"})
        return
    }
    // POST: authenticate
    email := ctx.FormValue("email")
    pass := ctx.FormValue("password")

    // require Bun to be configured for DB-backed auth
    if ctx.App == nil || ctx.App.Bun() == nil {
        _ = ctx.AddFlash("error", "server not configured for DB-backed auth")
        ctx.Redirect("/login", 302)
        return
    }

    // lookup user (simple anonymous struct to avoid cross-package model import)
    var u struct {
        ID           int64  ` + "`bun:\"id\"`" + `
        Email        string ` + "`bun:\"email\"`" + `
        PasswordHash string ` + "`bun:\"password_hash\"`" + `
        Role         string ` + "`bun:\"role\"`" + `
    }
    err := ctx.App.Bun().NewSelect().Model(&u).Where("email = ?", email).Scan(context.Background())
    if err != nil {
        _ = ctx.AddFlash("error", "invalid credentials")
        _ = ctx.Render("auth/login", map[string]interface{}{"Title": "Login", "Email": email})
        return
    }
    if bcrypt.CompareHashAndPassword([]byte(u.PasswordHash), []byte(pass)) != nil {
        _ = ctx.AddFlash("error", "invalid credentials")
        _ = ctx.Render("auth/login", map[string]interface{}{"Title": "Login", "Email": email})
        return
    }

    // success: set session
    sess := ctx.Session()
    if sess != nil {
        _ = sess.Set("user_id", u.ID)
        _ = sess.Set("user_role", u.Role)
    }
    ctx.Redirect("/", 302)
}

func (c *AuthController) Logout(ctx *flow.Context) {
    s := ctx.Session()
    if s != nil {
        _ = s.Delete("user_id")
        _ = s.Delete("user_role")
    }
    ctx.Redirect("/", 302)
}
`

var viewAuthLoginTmpl = `<h1>Login</h1>
{{with .Flash}}<div class="flash">{{.}}</div>{{end}}
<form method="post" action="/login">
  <label>Email: <input type="email" name="email" value="{{.Email}}"></label>
  <label>Password: <input type="password" name="password"></label>
  <button type="submit">Login</button>
</form>`

var authMiddlewareTmpl = `// Code generated by flow generate auth middleware; DO NOT EDIT.
package middleware

import (
    "net/http"
    flow "github.com/dministrator/flow/pkg/flow"
)

// RequireLogin redirects unauthenticated requests to /login. It relies on
// session keys set by the login controller (user_id).
func RequireLogin() flow.Middleware {
    return func(next http.Handler) http.Handler {
        return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
            s := flow.FromContext(r.Context())
            if s == nil {
                http.Redirect(w, r, "/login", http.StatusFound)
                return
            }
            if _, ok := s.Get("user_id"); !ok {
                http.Redirect(w, r, "/login", http.StatusFound)
                return
            }
            next.ServeHTTP(w, r)
        })
    }
}

// RequireRole returns middleware that ensures the session's user_role
// matches the provided role. It first checks the session and denies if not present.
func RequireRole(role string) flow.Middleware {
    return func(next http.Handler) http.Handler {
        return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
            s := flow.FromContext(r.Context())
            if s == nil {
                http.Error(w, "forbidden", http.StatusForbidden)
                return
            }
            if v, ok := s.Get("user_role"); ok {
                if rv, ok2 := v.(string); ok2 && rv == role {
                    next.ServeHTTP(w, r)
                    return
                }
            }
            http.Error(w, "forbidden", http.StatusForbidden)
        })
    }
}
`

var authReadmeTmpl = `# Auth scaffold

This folder contains generated auth scaffolding: a login/logout controller,
login view, and middleware helpers. The generator also creates a ` + "`User`" + ` model and migrations.

Mount the middleware in your main application to protect routes. Example:

    // in main.go
    import "app/middleware"
    app.Use(middleware.RequireLogin())

The generated auth controller uses bcrypt for password verification and Bun
for DB lookups. Ensure your ` + "`App`" + ` is configured with Bun (` + "`app.SetBun(...)`" + `) before using the login handlers.
`
