package generator

var controllerTmpl = `// Code generated by flow generate; DO NOT EDIT.
package {{.Package}}

import (
    "net/http"
    flow "github.com/dministrator/flow/pkg/flow"
)

// {{.Controller}} is a simple controller generated by Flow.
type {{.Controller}} struct{ *flow.Controller }

func New{{.Controller}}(app *flow.App) *{{.Controller}} {
    return &{{.Controller}}{Controller: flow.NewController(app)}
}

func (c *{{.Controller}}) Index(ctx *flow.Context) {
    ctx.JSON(200, map[string]string{"action": "index"})
}

func (c *{{.Controller}}) Show(ctx *flow.Context) {
    id := ctx.Param("id")
    ctx.JSON(200, map[string]string{"id": id})
}
`

// removed unused generated model template (bunModelTmpl is used instead)

// bunModelTmpl is a model template that includes bun struct tags which are
// friendly to the bun ORM adapter. Generators will use this when bun is the
// chosen adapter.
var bunModelTmpl = `// Code generated by flow generate; DO NOT EDIT.
package {{.Package}}

import (
    "context"
    "github.com/dministrator/flow/pkg/flow"
{{.ExtraImports}}
)

// {{.Model}} is a generated model using bun struct tags.
type {{.Model}} struct {
    flow.Model
{{.FieldsCode}}
}

// Save persists the model. It inserts when ID==0 or updates otherwise.
func (m *{{.Model}}) Save(ctx context.Context, app *flow.App) error {
    if m.ID == 0 {
        return flow.Insert(ctx, app, m)
    }
    return flow.Update(ctx, app, m)
}

// Delete removes the model from the database.
func (m *{{.Model}}) Delete(ctx context.Context, app *flow.App) error {
    return flow.Delete(ctx, app, m)
}
`

var migrationUpTmpl = `-- Migration: {{.Timestamp}}_create_{{.Table}}.up.sql
-- Generated by flow
CREATE TABLE IF NOT EXISTS {{.Table}} (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL
{{.Columns}}
);
{{.ExtrasUp}}
`

var migrationDownTmpl = `-- Migration: {{.Timestamp}}_create_{{.Table}}.down.sql
-- Generated by flow
{{.ExtrasDown}}
DROP TABLE IF EXISTS {{.Table}};
`

var viewIndexTmpl = `<h1>{{.Title}} index</h1>
<ul>
{{range .Items}}  <li>{{.}}</li>
{{end}}</ul>`

var viewShowTmpl = `<h1>{{.Title}} show</h1>
<p>ID: {{.ID}}</p>`

var viewNewTmpl = `<h1>New {{.Title}}</h1>
<form method="post" action="">
    <!-- TODO: fields -->
    <button type="submit">Create</button>
</form>`

var viewEditTmpl = `<h1>Edit {{.Title}}</h1>
<form method="post" action="">
    <!-- TODO: fields -->
    <button type="submit">Save</button>
</form>`

// Admin templates
var adminControllerTmpl = `// Code generated by flow generate admin; DO NOT EDIT.
package controllers

import (
    "github.com/dministrator/flow/pkg/flow"
)

type {{.Controller}} struct{ *flow.Controller }

func New{{.Controller}}(app *flow.App) *{{.Controller}} {
    return &{{.Controller}}{Controller: flow.NewController(app)}
}

func (c *{{.Controller}}) Index(ctx *flow.Context) {
    // TODO: replace with real list retrieval
    ctx.Render("admin/{{.Name}}/index", map[string]interface{}{"Title": "{{.Title}}"}, ctx)
}

func (c *{{.Controller}}) Show(ctx *flow.Context) {
    id := ctx.Param("id")
    ctx.Render("admin/{{.Name}}/show", map[string]interface{}{"Title": "{{.Title}}", "ID": id}, ctx)
}

func (c *{{.Controller}}) New(ctx *flow.Context) {
    ctx.Render("admin/{{.Name}}/new", map[string]interface{}{"Title": "New {{.Title}}"}, ctx)
}

func (c *{{.Controller}}) Create(ctx *flow.Context) {
    // TODO: implement creation logic (bind form, persist)
    ctx.Redirect(302, "/admin/{{.Name}}")
}

func (c *{{.Controller}}) Edit(ctx *flow.Context) {
    id := ctx.Param("id")
    ctx.Render("admin/{{.Name}}/edit", map[string]interface{}{"Title": "Edit {{.Title}}", "ID": id}, ctx)
}

func (c *{{.Controller}}) Update(ctx *flow.Context) {
    // TODO: implement update logic
    ctx.Redirect(302, "/admin/{{.Name}}")
}

func (c *{{.Controller}}) Delete(ctx *flow.Context) {
    // TODO: implement delete logic
    ctx.Redirect(302, "/admin/{{.Name}}")
}

// MountAdminRoutes registers admin routes for this resource.
func MountAdmin{{.Controller}}Routes(app *flow.App) {
    r := flow.NewRouter(app)
    ctrl := New{{.Controller}}(app)
    base := "/admin/{{.Name}}"
    r.Get(base, ctrl.Index)
    r.Get(base+"/new", ctrl.New)
    r.Post(base, ctrl.Create)
    r.Get(base+"/:id", ctrl.Show)
    r.Get(base+"/:id/edit", ctrl.Edit)
    r.Post(base+"/:id", ctrl.Update)
    r.Post(base+"/:id/delete", ctrl.Delete)
    app.Mount(r)
}
`

var viewAdminIndexTmpl = `<h1>{{.Title}} - index</h1>
<p><a href="/admin/{{.Name}}/new">New</a></p>
<ul>
  <!-- TODO: render items -->
  <li>Example item</li>
</ul>`

var viewAdminShowTmpl = `<h1>{{.Title}} - show</h1>
<p>ID: {{.ID}}</p>
<p><a href="/admin/{{.Name}}">Back</a></p>`

var viewAdminNewTmpl = `<h1>New {{.Title}}</h1>
<form method="post" action="/admin/{{.Name}}">
    <!-- TODO: form fields -->
    <button type="submit">Create</button>
</form>`

var viewAdminEditTmpl = `<h1>Edit {{.Title}}</h1>
<form method="post" action="/admin/{{.Name}}/{{.ID}}">
    <!-- TODO: form fields -->
    <button type="submit">Save</button>
</form>`

var adminLayoutTmpl = `<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Admin - {{.Title}}</title>
  <link rel="stylesheet" href="/assets/admin/admin.css">
  <style>body{font-family:Arial,Helvetica,sans-serif;padding:20px}</style>
</head>
<body>
  <nav><a href="/admin">Admin</a> | <a href="/">Home</a></nav>
  <div id="flash">{{/* TODO: flash messages */}}</div>
  <main>{{ template "content" . }}</main>
</body>
</html>`

var adminCSSTmpl = `/* Minimal admin CSS */
body { background:#f7f7f7; color:#111 }
nav { margin-bottom: 1em }
main { background:#fff; padding:1em; border-radius:6px }
`

var adminReadmeTmpl = `# Admin scaffold

This folder contains generated admin UI scaffolding (controllers, views, routes).

To mount the admin routes in your application main, call the generated mount function in your main.go. For example:

    // inside main
    MountAdminPostsRoutes(app)

Replace or implement TODOs in the generated controller actions to add persistence and validation.
`
