name: golangci-lint

on:
  pull_request:
  push:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.59.0
          args: run ./...
